version: "3.5"
services:
  mysql_eicaa:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eicaa
      MYSQL_DATABASE: eicaa
    volumes:
      - ./database_data:/var/lib/mysql
    healthcheck:
      test: mysql eicaa --user=root --password='eicaa' --silent --execute "SELECT 1;"
      interval: 20s
      timeout: 5s
      retries: 15
    network_mode: "host"
  express_eicaa:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql_eicaa
    network_mode: "host"