version: "3.5"

services:

  mysql_eicaa:
    container_name: eicaa_backend_mysql
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eicaa
      MYSQL_DATABASE: eicaa
    volumes:
      - ./database_data:/var/lib/mysql
    healthcheck:
      test: mysql eicaa --user=root --password='eicaa' --silent --execute "SELECT 1;"
      interval: 20s
      timeout: 5s
      retries: 15
    networks:
      - eicaa

  express_eicaa:
    container_name: eicaa_backend_app
    build: .
    image: eicaa-backend:latest
    ports:
      - 127.0.0.1:3200:3200
    env_file: ./.env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql_eicaa
    networks:
      - eicaa

networks:
  eicaa:
    name: "eicaa-network"
    ipam:
      driver: default
      config:
      - subnet: "172.99.0.0/24"